  server:
      port: 8088

  spring:
    datasource:
      username: root
      password: wukuiqing0
      url: jdbc:mysql://127.0.0.1:3306/Demo
      driver-class-name: com.mysql.jdbc.Driver
      #  阿里巴巴 druid    配置数据源
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validaionQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters 去掉后监控界面sql无法统计，‘wall’用于防火墙
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500
      stat-view-servlet:
        enabled:true




